FROM bitwalker/alpine-erlang:20.2.2

# Set exposed ports
EXPOSE 5000

# Set environment variables
ENV MIX_ENV=prod

# Copy tarball release
ADD _build/prod/rel/docknix/releases/0.0.1/docknix.tar.gz ./

# Set user
USER default

# Set entrypoint
ENTRYPOINT ["./bin/docknix"]
