FROM bitwalker/alpine-elixir-phoenix:1.6.1

ENV MIX_ENV prod

# Add the files to the image
ADD . .

# Cache Elixir deps
RUN mix deps.get --only prod
RUN mix deps.compile

# Change to assets directory
WORKDIR assets

# Cache Node deps
RUN npm i

# Compile JavaScript
RUN npm run deploy

# Change back to project root
WORKDIR ..

# Compile app
RUN mix compile
RUN mix phx.digest

# Generate release
ENTRYPOINT ["mix"]
CMD ["release", "--env=prod"]
