version: 2
jobs:
  build:
    docker:
      # Bump cache key version below when changing elixir version
      - image: circleci/elixir:1.6.1

    # Env vars, could also be set in CircleCI app settings
    environment:
      - APP_NAME: docknix
      - APP_VERSION: 0.0.1

    steps:
      - checkout

      # Ensure system dependencies are available for deployment
      - run:
          name: Install some system dependencies
          command: sudo apt-get update -qq && sudo apt-get install -y ssh rsync

      # Install Docker
      - run:
          name: Install Docker
          command: |
              sudo apt-get -y install \
                  apt-transport-https \
                  ca-certificates \
                  curl \
                  software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository \
                 "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                 $(lsb_release -cs) \
                 stable"
              DEBIAN_FRONTEND=noninteractive sudo apt-get -y update
              sudo apt-get -y install docker-ce

      # Build with Docker
      - run:
          name: Build everything
          command: ./build.sh

      # Deploy
      - deploy:
          name: Deploy to Production
          command: |
            ssh-keyscan -H $APP_HOST >> ~/.ssh/known_hosts;
            rsync -ravhz --stats --progress _build/prod/rel/$APP_NAME/releases/$APP_VERSION/$APP_NAME.tar.gz $APP_USER@$APP_HOST:/home/$APP_USER/apps/$APP_NAME/_build/prod/rel/$APP_NAME/releases/$APP_VERSION/;
            rsync -ravhz --stats --progress nginx/ $APP_USER@$APP_HOST:/home/$APP_USER/nginx;
            rsync -ravhz --stats --progress Dockerfile.run $APP_USER@$APP_HOST:/home/$APP_USER/apps/$APP_NAME;
            rsync -ravhz --stats --progress docker-compose.yml $APP_USER@$APP_HOST:/home/$APP_USER/apps/$APP_NAME;
      - deploy:
          name: Post-deploy and app restart on production
          command: ./.circleci/post-deploy.sh
