version: 2
jobs:
  build:
    docker:
      # Bump cache key version below when changing elixir version
      - image: circleci/elixir:1.6.1

    # Env vars, could also be set in CircleCI app settings
    environment:
      - APP_NAME: docknix
      - APP_VERSION: 0.0.1

    steps:
      - checkout
      - setup_remote_docker

      # Ensure system dependencies are available for deployment
      - run:
          name: Install some system dependencies
          command: sudo apt-get update -qq && sudo apt-get install -y ssh rsync

      # Build with Docker
      - run:
          name: Build everything
          command: ./build.sh

      - run:
          name: Copy build artifacts
          command: |
            docker ps -a
            docker cp docknix-build:docknix.tar.gz docknix.tar.gz

      # Deploy
      - deploy:
          name: Deploy to Production
          command: |
            ssh-keyscan -H $APP_HOST >> ~/.ssh/known_hosts;
            ls -al;
            rsync -ravhz --stats --progress _build/prod/rel/$APP_NAME/releases/$APP_VERSION/$APP_NAME.tar.gz $APP_USER@$APP_HOST:/home/$APP_USER/apps/$APP_NAME/_build/prod/rel/$APP_NAME/releases/$APP_VERSION/;
            rsync -ravhz --stats --progress nginx/ $APP_USER@$APP_HOST:/home/$APP_USER/nginx;
            rsync -ravhz --stats --progress Dockerfile.run $APP_USER@$APP_HOST:/home/$APP_USER/apps/$APP_NAME;
            rsync -ravhz --stats --progress docker-compose.yml $APP_USER@$APP_HOST:/home/$APP_USER/apps/$APP_NAME;
      - deploy:
          name: Post-deploy and app restart on production
          command: ./.circleci/post-deploy.sh
